### ISSUE TITLE
No sound on Apple

### ISSUE THREAD

**Issue by mmgnservices** [CodeYan01/media-playlist-source#16]
Hi,
We face issue with the sound, media sound is not detected.
MacBook CPU intel I7, 16GB of Ram Latest Osx version.
OBS 29.3.1

**Comment by CodeYan01** [comment]
Does the audio mixer move?

**Comment by mmgnservices** [comment]
Hi
No, it not add audio mixer.

When you add a media input is supposed to add a line input on the mixer.
The playlist don't add it.

**Comment by CodeYan01** [comment]
Can you please turn off Studio Mode and take a screenshot of the issue?

**Comment by mmgnservices** [comment]
On studio mode turned off and  show the audio mixer, the problem loo on Studio mode.

￼
￼




Gaston Della Valle 
Sales Manager and CEO

Skype: glavalle2011
Phone: (888) 202-7592
Email: ***@***.***
Web: https://www.mmgnservices.com


CONFIDENTIALITY NOTICE:
All information transmitted hereby is intended only for the use of the addressee(s) named above and may contain confidential and privileged information.  Any unauthorized review, use, disclosure or distribution of confidential and/or privileged information is prohibited.  If the reader of this message is not the intended recipient(s) you are hereby notified that you must not read this transmission and that disclosure, copying, printing, distribution or use of any of the information contained in or attached to this transmission is prohibited.  Anyone who receives confidential and/or privileged information in error should notify us immediately by replying to the sender of the message, mail the original message to us at the above address and destroy all copies.

**Comment by CodeYan01** [comment]
This is not an issue of the plugin. The reason it doesn't work on Studio mode is because you have just added the source. In Studio Mode, new sources (any kind of source) do not automatically get into the program output, and as such, would not be added to the audio mixer. In order for it to appear, you have to transition to the same scene first. The source appearing in the audio mixer when Studio Mode is off confirms this.
